### ISSUE TITLE
Provide an option to use the built-in modules support in Gradle 6.4 and later

### ISSUE THREAD

**Issue by msgilligan** [beryx/badass-jar#2]
The README says:

> If the plugin detects that at least one of sourceCompatibility and targetCompatibility has an effective value >= 9, it automatically applies the gradle-modules-plugin, which adds support for the JPMS. 

Is it possible to add an option to not apply the gradle-modules-plugin, when using Gradle 6.4 or later? That would possibly make this plugin even lighter-weight and hopefully reduce plugin interaction/compatibility issues in the future.

**Comment by msgilligan** [comment]
(I suppose another alternative would be to create a 2.0 version that requires Gradle 6.4 or later)

**Comment by siordache** [comment]
You're right, creating a 2.0 version is the best option.

**Comment by siordache** [comment]
Version 2.0.0-rc-1 released (requires Gradle 6.4 or later).

**Comment by msgilligan** [comment]
Thanks for making the 2.0.0-rc-1 release!

I'm testing out 2.0.0-rc-1 on my [Supernaut.FX](https://github.com/SupernautApp/SupernautFX) build. Prior to using the plugin the three modules being built were as follow:

* `app.supernaut` - JDK 9
* `app.supernaut.fx` - JDK 11 (uses JavaFX)
* `app.supernaut.fx.micronaut` - JDK 11 (uses JavaFX)

I tried to make the `app.supernaut` module a JDK 8 module using the plugin with this commit: https://github.com/SupernautApp/SupernautFX/commit/8a6b9cc641d64902a0c48225342237bc89a11dc8

The main build (see Github Actions) is working, but I've stumbled on issues related to the following:

1. Multiproject Gradle
2. The Gradle Java Toolchains feature
3. Using `options.release` instead of `sourceCompatibility`
4. Problems configuring custom JavaDoc tasks 

The specific issues I've encountered are:

A. Sibling subprojects in IntelliJ don't know about the plugin, so they fail to see the `module-info`.

B. The documented method of using `-PjavaCompatibility=11` doesn't apply to multi-project well.

C.  You can't use `-PjavaCompatibility=11` at all if using the Java Toolchains feature:

```
Execution failed for task ':modules:app.supernaut:compileJava'.
> The new Java toolchain feature cannot be used at the project level in combination with source and/or target compatibility
```

D. IntelliJ IDEA does something when loading the `build.gradle` that causes the `Java toolchain feature cannot be used at the project level` message to be displayed.

E. I had to add a redundant `sourceCompatibility = 8` to my `build.gradle` even though I had `options.release = 8` set.

F. I had to disable my `mergedJavadoc` task, because I couldn't figure out how to tell it about the `module-info.java` file being in a different location.

Overall, it seems that for the Supernaut.FX project the best approach would probably be to configure the `app.supernaut` sub-project as much as possible as a Java 9 project and activate the build of the Java 8 JAR via a command-line switch when making the official build.

p.s. I'm happy to open new issues for any of these if you want, but I thought I'd start by grouping them all in this existing issue.

**Comment by siordache** [comment]
I just released 2.0.0-rc-3, which addresses most of the above issues. One breaking change is that the `modularity` extension of the `jar` task has been replaced by a top-level extension named `moduleConfig` (see the [README](https://github.com/beryx/badass-jar-plugin/blob/master/README.adoc)).

The plugin no longer uses the `javaCompatibility` property. However, users can implement their own mechanisms for switching between compiling with Java 8 and 11.

Placing `module-info.java` in a non-standard location is now discouraged unless you exclusively use a Java 8 toolchain.

Starting from the https://github.com/SupernautApp/SupernautFX/commit/8a6b9cc641d64902a0c48225342237bc89a11dc8 commit and moving `module-info.java` back to `src/main/java`, I used the following build.gradle to create the modular jar:

```gradle
plugins {
    id 'java-library'
    id 'org.beryx.jar' version '2.0.0-rc-3'
}

//java {
//    modularity.inferModulePath = true // no longer required since Gradle 7.0
//}

moduleConfig {
    multiRelease = false
}

compileJava {
    options.release = (findProperty('javaCompatibility') ?: 11) as int
}

dependencies {
    // No Dependencies!!
}
```

The default `options.release` is 11 in order to avoid issues with IntelliJ IDEA. To create a Java 8 JAR, you need to run Gradle with `-PjavaCompatibility=8`.

**Comment by msgilligan** [comment]
`2.0.0-rc-3` looks great and seems to address all of my issues. Thank you!

I have a draft PR https://github.com/SupernautApp/SupernautFX/pull/29 which I plan to merge and use in the next release of Supernaut.FX.

**Comment by siordache** [comment]
Currently, the plugin creates by default a multi-release jar. I'm thinking of changing the default to putting the module-info.class in the root of the jar, as suggested by @sormuras. This would allow me to replace the properties `multiRelease` and `moduleInfoCompatibility` with a single one, named for example `multiReleaseVersion`. Leaving this property unset, the module-info.class will be put in the root of the jar. What do you think?

**Comment by msgilligan** [comment]
>  What do you think?

Sounds right to me. @sormuras argument has won me over, I'm doing "module-info in root" for Supernaut.FX, and it looks like [Jakarta is going to standardize on it for EE 10](https://github.com/eclipse-ee4j/injection-api/releases/tag/2.0.1.MR). So the two advantages of this approach are:

1. The default is the industry-standard/best-practice
2. Fewer config variables.

**Comment by msgilligan** [comment]
> The default `options.release` is 11 in order to avoid issues with IntelliJ IDEA. 

What were the issues with IDEA? I would like to default `options.release` to `9` to protect against using newer versions of the Java API. (Of course, I really want the IDE to only allow use of JDK 8 APIs)

**Comment by siordache** [comment]
You can safely default to 9. IDEA has issues only when `option.release` is 8.

**Comment by msgilligan** [comment]
> You can safely default to 9. IDEA has issues only when `option.release` is 8.

Thanks! (https://github.com/SupernautApp/SupernautFX/commit/742bb3694e24a0624f7e5b3dee017be03b0f8137)

**Comment by siordache** [comment]
`2.0.0-rc-4` released with `multiReleaseVersion` replacing `multiRelease` and `moduleInfoCompatibility`.

**Comment by msgilligan** [comment]
> `2.0.0-rc-4` released with `multiReleaseVersion` replacing `multiRelease` and `moduleInfoCompatibility`.

https://github.com/SupernautApp/SupernautFX/commit/ca7fe805b3292b310653d972da4ef23cf45d7dbd

I'm wondering what I should do about `moduleConfig.version`. I guess I can't set it to `project.version` if I'm using `-SNAPSHOT` versions?

**Comment by sormuras** [comment]
Try passing various version strings to `ModuleDescriptor.Version.parse()` : https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/module/ModuleDescriptor.Version.html

Iirc, semver plus `-SNAPSHOT` are fine.

**Comment by siordache** [comment]
Virtually every version string that starts with a digit is fine.

**Comment by msgilligan** [comment]
My Supernaut.FX PR https://github.com/SupernautApp/SupernautFX/pull/29 is now using `2.0.0-rc-5` and is looking good!

**Comment by msgilligan** [comment]
Update... I merged https://github.com/SupernautApp/SupernautFX/pull/29 into `master`, so the next release will use this plugin.
