### ISSUE TITLE
Set module version

### ISSUE THREAD

**Issue by sormuras** [beryx/badass-jar#3]
Does this plugin support setting module version information, like `jar --create --file ... --module-version X`?

PS: Installing and applying this plugin here: https://github.com/jlink/jqwik/issues/243

**Comment by siordache** [comment]
Coming soon...

**Comment by sormuras** [comment]
...thanks in advance, Serban! 🤓

**Comment by siordache** [comment]
Implemented in 2.0.0-rc-2: https://github.com/beryx/badass-jar-plugin#module-version.

**Comment by sormuras** [comment]
Very nice. Testing it in a minute...

**Comment by sormuras** [comment]
...reading the lines you added to the README text, I assume that this plugin now always adds the version to modules. Right?

If yes, that may be problematic when the (Maven) version string does adhere to Java module version syntax described here:

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/module/ModuleDescriptor.Version.html

Perhaps it's better (safer) to not include the project's into modules by default.

**Comment by siordache** [comment]
In 2.0.0-rc-3 the plugin no longer sets the module version by default.

**Comment by siordache** [comment]
And in 2.0.0-rc-4 it puts by default the `module-info.class` in the root of the jar.

**Comment by sormuras** [comment]
That are all in all better defaults, methinks. +1

**Comment by msgilligan** [comment]
@siordache @sormuras Can we close this issue?

**Comment by siordache** [comment]
Yes, closing.
