### ISSUE TITLE
Document tradeoffs between approaches (especially as to how it affects your IDE)

### ISSUE THREAD

**Issue by msgilligan** [beryx/badass-jar#4]
Using the `badass-jar-plugin`, there are two paths you can go by: 

1. Have the "default view" of the project be a Java 9+, modular world and in a full/release build use a command-line flag to tell the plugin to create JDK 8 versions of the target JARs (i.e. `src/main/java/module-info.java`)

2. Have the "default view" of the project be Java 8, non-modular and use the plugin to add `module-info` to the target JARs. (i.e. `src/main/module/module-info.java`)

The advantage to (1) is that your IDE can validate your `module-info` as you develop (this can be especially important in multi-project builds.) The advantage to (2) is that your IDE can validate your use of the Java API as you develop.

Personally, I'm just beginning to experiment with and understand these trade-offs and I only use IDEA on a regular basis, so even as I do learn more I'll only understand how it works in one IDE.

It would be nice if there was a place to document some of these issues -- not sure if the `README` is the right place.

**Comment by siordache** [comment]
One option is [the Wiki](https://github.com/beryx/badass-jar-plugin/wiki). I configured it to be open for editing to anyone.

**Comment by msgilligan** [comment]
I added a wiki page: https://github.com/beryx/badass-jar-plugin/wiki/Projects-using-badass-jar-plugin

**Comment by msgilligan** [comment]
https://github.com/beryx/badass-jar-plugin/wiki/Projects-using-badass-jar-plugin is updated and includes the note:

> In **IntelliJ IDEA** the project uses the default JDK 9, so IDEA is aware of modules as you are developing. One downside to this approach is that IDEA will allow you to use JDK 9 API features (e.g. `List.of()`) without providing a warning. Building with the setting that enables JDK 8 (in this case `-PbaseModuleJavaCompatibility=8`) will fail if JDK 9 or later APIs are used, but it would be better if these errors could be detected immediately while working in the IDE.

This seems to be the only IDE issue I'm experiencing. It would be nice if IntelliJ let you configure a subproject/"module" to allow `module-info`, but otherwise enforce JDK 8 compatibility.
