### ISSUE TITLE
Upgrading from 2.0.0-rc-2 to 2.0.0-rc-4 fails

### ISSUE THREAD

**Issue by sormuras** [beryx/badass-jar#5]
https://github.com/jlink/jqwik/pull/249

Is it failing due to (removed?) `multiRelease` property?

https://github.com/jlink/jqwik/blob/4f3e648a1a3208f6aa888809b852e6de2e19a18c/api/build.gradle#L6-L9

**Comment by siordache** [comment]
Yes, there are some breaking changes in 2.0.0-rc-4. 


You need to replace

```
jar {
	archiveBaseName.set('jqwik-api')
	archiveVersion.set("${jqwikVersion}")	
	modularity {
		multiRelease = false // store module descriptor in JAR's root
		moduleInfoPath = 'src/main/module/module-info.java' // don't confuse IDEs
	}
}
```


with

```
moduleConfig {
	moduleInfoPath = 'src/main/module/module-info.java' // don't confuse IDEs
	neverCompileModuleInfo = true
}

jar {
	archiveBaseName.set('jqwik-api')
	archiveVersion.set("${jqwikVersion}")
}
```

And use **2.0.0-rc-5**. It fixes a problem that also affects your build.

**Comment by sormuras** [comment]
After upgrading to `2.0.0-rc5` and updating the `moduleConfig` blocks, it works.

There are some related questions in this PR: https://github.com/jlink/jqwik/pull/253 -- care to take a look? TIA!
